# Document Generator Configuration
document.count=90000
api.url=http://localhost:8080/api/documents
http.connectTimeoutSec=5
http.socketTimeoutSec=10
http.responseTimeoutSec=20
multithreading.timeout=5
logging.initialDelay = 50
logging.period = 4