ALTER TABLE documents
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE document_history
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE approval_registry
    ALTER COLUMN approved_at TYPE TIMESTAMP WITH TIME ZONE;